x-default-resources: &default-resources
  deploy:
    resources:
      limits:
        cpus: '1'
        memory: 256M
      reservations:
        cpus: '0.5'
        memory: 120M
  restart: unless-stopped
  networks:
    - network

services:
  # server:
  #   <<: *default-resources 
  #   container_name: ${CONTAINER_PREFIX}_server
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8081:8080
  #   networks:
  #     - network
  #   depends_on:
  #     redis:
  #       condition: service_healthy

  db:
    <<: *default-resources 
    image: postgres:16-alpine
    container_name: ${CONTAINER_PREFIX}_postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} 
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USERNAME}  -d ${POSTGRES_DB} -t 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

  redis:
    <<: *default-resources 
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 520M
    container_name: ${CONTAINER_PREFIX}_redis
 
    image: redis:7.2.6-alpine
    ports:
      - 6377:6377
    volumes:
      - redis-data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [
        "redis-server",
        "/usr/local/etc/redis/redis.conf",
      ]
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6377", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
      
  minio:
    <<: *default-resources 
    image: minio/minio:latest
    container_name: ${CONTAINER_PREFIX}_minio
    ports:
      - "9110:9000"
      - "9111:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 10s
  minio-cli:
    <<: *default-resources 
    image: minio/mc:latest
    container_name: ${CONTAINER_PREFIX}_minio_cli
    build:
      context: ./minio
      dockerfile: Dockerfile
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      S3_BUCKET_ID: ${S3_BUCKET_ID}
      S3_ENDPOINT: "http://minio:9000"
    volumes:
      # - ./minio/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ./minio/config/policy.json:/tmp/policy.json     
networks:
  network:
    name: ${CONTAINER_PREFIX}
    driver: bridge
volumes:  
  minio-data:
    name: ${CONTAINER_PREFIX}_minio
  redis-data:
    name: ${CONTAINER_PREFIX}_redis
  pg_data:
    name: ${CONTAINER_PREFIX}_postgres
