FROM node:18-bookworm-slim

WORKDIR /app

COPY package*.json ./

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

# Replace .env with .env.production
RUN if [ -f .env.production ]; then cp .env.production .env; fi

RUN pnpm run build 

CMD pnpm run start:prod