name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Focused Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      # Run only the billing calculation unit tests
      - name: Run Billing Unit Tests
        run: npm test -- usage.service.spec.ts --testNamePattern="Billing Calculations"
        env:
          TEST_FOCUS: 'unit'
      
      # Run only the async workflow integration tests  
      - name: Run Integration Tests
        run: npm test -- usage.integration.spec.ts --testNamePattern="Complete Flow"
        env:
          TEST_FOCUS: 'integration'

  lint:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'  # Changed from npm to pnpm since you're using pnpm
      
      - name: Install dependencies
        run: pnpm install  # Changed from npm ci
      
      - name: Run ESLint
        run: pnpm lint
      
      - name: Run TypeScript type checking
        run: pnpm build -- --noEmit  # More thorough than just type-check
      
      - name: Check formatting with Prettier
        run: pnpm format --list-different