name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Focused Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      # Run only the billing calculation unit tests
      - name: Run Billing Unit Tests
        run: pnpm test -- usage.service.spec.ts --testNamePattern="Billing Calculations"
        env:
          TEST_FOCUS: 'unit'
      
      # Run only the async workflow integration tests  
      - name: Run Integration Tests
        run: pnpm test -- usage.integration.spec.ts --testNamePattern="Complete Flow"
        env:
          TEST_FOCUS: 'integration'

  lint:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run ESLint
        run: pnpm lint
      
      - name: Run TypeScript type checking
        run: pnpm build -- --noEmit
      
      - name: Check formatting with Prettier
        run: pnpm format --list-different